### PR TITLE
65 create incorrect username or password alert and succesfully signed up alert

### PR DESCRIPTION
**Pull request by K-Straiton**
I have added alerts that will show on the login page. These alerts include:
-  An error alert when username or password is incorrect
image
- An error alert that shows up after being redirected to login after attempting to make a post without being signed in
image
- An error alert that shows up after being redirected to login after attempting to post a comment without being signed in
image
- A success alert when redirected to login after successfully signing up
image

I have also changed the style of the errors that appear on the sign up page when fields are incorrect. They now use the bootstrap 'is-invalid' class and style for errors instead of plain spans.

image

### CODE REVIEW

**Review by Sebagabones — COMMENTED** [review]
Hmm - I really like this, the only thing I can think of suggesting is changing the please chose a different username to something that explains why, as in, this username is already taken, just to save confusion as to why you'd need to choose a different one (as one may think they can't use certain characters) - open for discussion

**Comment by laurenpudz** [comment]
> Hmm - I really like this, the only thing I can think of suggesting is changing the please chose a different username to something that explains why, as in, this username is already taken, just to save confusion as to why you'd need to choose a different one (as one may think they can't use certain characters) - open for discussion

I think that this would be a really good idea! Would be useful for users to have more detail as to why they need a different username (and so they don't start removing special characters for no reason)

**Review by sersangn — APPROVED** [review]
Alerts look good! In terms of styling, I think the "Please choose a different username" could be made smaller. Also I second what Seb says about maybe having it more descriptive to include why the username/password is not valid

**Comment by Sebagabones** [comment]
Another thing - do the same thing that you have done on the sign up page to the create a post/comments (and titles) for if a post is too long

**Comment by K-Straiton** [comment]
> Another thing - do the same thing that you have done on the sign up page to the create a post/comments (and titles) for if a post is too long

Currently, when typing in those fields it does not let you go over the limit, it just stops typing, so anything that gets submitted with be the correct maximum length, so adding an error would not be possible as it is.

**Comment by K-Straiton** [comment]
> Alerts look good! In terms of styling, I think the "Please choose a different username" could be made smaller. Also I second what Seb says about maybe having it more descriptive to include why the username/password is not valid

I tested out a smaller font size and Seb and I both prefer the slightly larger font size.

**Review by Sebagabones — APPROVED** [review]
Perfect :) - thanks for adding those changes to username on signup page!
Happy for you to merge it now!

**Review by laurenpudz — APPROVED** [review]
Changes look good, thanks for making those adjustments! Happy to merge.

**Pull request merged**
