### PR TITLE
Add user view

### PR DESCRIPTION
**Pull request by Sebagabones**

### CODE REVIEW

**Review by K-Straiton — APPROVED** [review]
Awesome! Looks good to me.

**Comment by laurenpudz** [comment]
When a user is logged in and they navigate to view their own profile through links/search, they are taken to the userview version of their profile, which doesnt have the option to edit thinkpad count and refers to the user in third person. 
This may be confusing as the userview and user's own profile page still look basically the same and the user may be confused as to why they have different options.
Should we redirect the user to their profile page when they attempt to access the userview version of their profile?

Everything else looks good, if the redirect isn't an issue then I'm happy to merge!

**Review by sersangn — CHANGES_REQUESTED** [review]
Second Lauren's comment, when the user is logged in, if they click their user profile link through search the view should redirect to the user view. Also, their is spelt wrong in the user profile page. Everything else looks good though!

Screenshot 2024-05-15 at 11 35 29 am

**Comment by Sebagabones** [comment]
Good points, spelling has been fixed, and now redirects to profile page if the user clicks on their own username

**Review by sersangn — APPROVED** [review]
Awesome looks good now!

**Pull request merged**
