### PR TITLE
41 add ability to change number of thinkpads on profile page

### PR DESCRIPTION
**Pull request by laurenpudz**
Create a modal on the profile page which allows user to edit the number of ThinkPads that they own. 
Number of ThinkPads is updated in the database and the profile page refreshes to provide updated data.

### CODE REVIEW

**Review by sersangn — APPROVED** [review]
Works well, happy to merge to main. Maybe one change that could be implemented is having an alert that says thinkpad number has been changed.

**Review by Sebagabones — CHANGES_REQUESTED** [review]
I think its good, but I would say we should maybe make the modal a little bit smaller

**Comment by K-Straiton** [comment]
> I think its good, but I would say we should maybe make the modal a little bit smaller

I tried and it unfortunately did not work so well. It will have to stay the size that it is for now.

**Review by Sebagabones — APPROVED** [review]
happy to leave the size as is :)

**Pull request merged**
