### PR TITLE
Change styling of links and cards 

### PR DESCRIPTION
**Pull request by laurenpudz**
Removed underline from all links. Changed styling of username links in post view to be random colours. Changed title links to be white. Altered margins on profile and home pages for better spacing.

### CODE REVIEW

**Review by Sebagabones — COMMENTED** [review]
heya - I think it would be good if we made the post body text clickable in index - thoughts? Happy to do it :)

**Comment by laurenpudz** [comment]
> heya - I think it would be good if we made the post body text clickable in index - thoughts? Happy to do it :)

Good idea! Thanks so much!

**Comment by Sebagabones** [comment]
Done - can you do a quick review of what I have done? I am happy with all of the changes you have made :)

**Comment by laurenpudz** [comment]
> Done - can you do a quick review of what I have done? I am happy with all of the changes you have made :)

Looks great, thanks for adding that feature

**Review by Sebagabones — APPROVED** [review]
I am happy with all the changes you have made now that I have made the post text clickable :)

**Review by sersangn — APPROVED** [review]
Looks a lot better now that the links aren't blue with the underline. Looks more cohesive.

**Review by K-Straiton — APPROVED** [review]
Awesome! Looks really good! I like having the body preview also clickable

**Pull request merged**
